export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_PAGE_NUMBER = 'UPDATE_PAGE_NUMBER';

export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const TOGGLE_SEARCH_INPUT = 'TOGGLE_SEARCH_INPUT';
export const UPDATE_SEARCH_INPUT_TEXT = 'UPDATE_SEARCH_INPUT_TEXT';

export const SHOW_DIALOG = 'SHOW_DIALOG';
export const HIDE_DIALOG = 'HIDE_DIALOG';
export const EDIT_POST = 'EDIT_POST';

export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_ERROR = 'GET_ARTICLE_ERROR';
